### PR TITLE
Configuring Travis script to use PostgreSQL 9.6

### PR DESCRIPTION
**Pull request by ethervoid**
- Added support to compile the extension for multiple Postgres versions if needed
- Refactor to move parts of the Travis YAML file to scripts to make it cleaner

Please @rafatower or @jgoizueta take a look please to merge it.

Once we merge this, we're going to broke the build because we don't support PostgreSQL yet.

There is a branch with the fix for postgresql that has this changes and the [build pass](https://travis-ci.org/CartoDB/odbc_fdw/builds/197417618)

### CODE REVIEW

**Comment by ethervoid** [comment]
Related to #42 

This is the first step, configure Travis build to compile and execute tests for PostgreSQL 9.5 and 9.6. 

The second step, #46, is pending of signing the CLA by @robe2

**Comment by ethervoid** [comment]
Yes I agree, I put them inside `travis` folder to be clear but `ci` seems to be more appropiate

**Comment by dgaubert** [comment]
Apart from that, I don't see anything else to comment. I feel someone from systems can help to review if packages and versions are the right choices in order to be closer to production env. But probably you did it before.

:es:

**Comment by pramsey** [comment]
I'm going to close this PR out, as we're now testing 9.6 in master.

**Pull request closed without merging**
